---

- name: join server to domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ ad_dns_domain_name }}"
    domain_ou_path: "{{ ad_domain_ou_path }}"
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: "{{ win_domain_admin_user }}"
    domain_admin_password: "{{ win_domain_admin_password }}"
    state: domain
  register: domain_state

- ansible.windows.win_reboot:
  when: domain_state.reboot_required

